import React from 'react';
import {createRoot} from 'react-dom/client';
import {Building2,House,Paintbrush,HardHat,Phone,Mail,MapPin,CheckCircle2,ArrowUpRight,ShieldCheck,Clock3,Gem,Menu} from 'lucide-react';
import './style.css';
const A=import.meta.env.BASE_URL;
const services=[
['Residential Construction',House,'03_Residential_Construction.jpg','Planning and execution support for homes, including structural and finishing activities according to project requirements.'],
['Commercial Construction',Building2,'04_Commercial_Construction.jpg','Construction solutions for commercial spaces with emphasis on functionality, coordination and durable execution.'],
['Interior Designing',Paintbrush,'02_About_Us_Engineering_Team.jpg','Interior planning and finishing concepts intended to create practical, comfortable and modern spaces.'],
['Maintenance & Repair',HardHat,'07_Quality_Safety_Surveying.jpg','Maintenance and repair support to help keep completed properties functional and in good condition.']];
const steps=['Requirement Discussion','Planning & Scope','Execution','Quality & Progress Review','Finishing & Handover','Maintenance Support'];
function App(){return <><header><a className="brand" href="#top"><img src={`${A}logo.png`}/><span><b>BABITA INFRA</b><small>PROJECTS PVT. LTD.</small></span></a><nav><a href="#about">About</a><a href="#services">Services</a><a href="#process">Process</a><a href="#contact">Contact</a></nav><a className="call" href="tel:7903528733"><Phone size={16}/>7903528733</a><Menu className="menu"/></header><main id="top">
<section className="hero"><img className="heroBg" src={`${A}01_Homepage_Hero.jpg`}/><div className="shade"/><div className="heroContent"><div className="pill">BUILDING CONSTRUCTION & MAINTENANCE</div><h1>Building tomorrow.<br/><em>Together.</em></h1><p>From foundations to finishing, we deliver thoughtfully planned residential and commercial spaces with a focus on workmanship, coordination and lasting value.</p><div className="actions"><a className="primary" href="tel:7903528733">Discuss your project <ArrowUpRight size={18}/></a><a className="ghost" href="#services">Explore services</a></div><div className="trust"><span><ShieldCheck/>Quality Construction</span><span><Clock3/>Timely Delivery</span><span><Gem/>Long Lasting Value</span></div></div></section>
<section id="about" className="about wrap"><div className="aboutImg"><img src={`${A}02_About_Us_Engineering_Team.jpg`}/><div className="badge"><b>BIPPL</b><span>Your Dream • Our Construction</span></div></div><div><div className="eyebrow">ABOUT US</div><h2>Practical construction.<br/>Professionally managed.</h2><p>Babita Infra Projects Pvt. Ltd. is a building construction and maintenance company focused on practical, durable and professionally managed solutions for residential and commercial projects.</p><p>Our approach centers on understanding client requirements, coordinating construction activities, maintaining workmanship standards and supporting properties beyond completion.</p><div className="checks"><span><CheckCircle2/>Transparent coordination</span><span><CheckCircle2/>Workmanship focus</span><span><CheckCircle2/>Client-first communication</span></div></div></section>
<section id="services" className="services"><div className="wrap"><div className="sectionHead"><div><div className="eyebrow">OUR SERVICES</div><h2>One team. Complete project support.</h2></div><p>Construction, interiors and ongoing maintenance designed around the requirements of each project.</p></div><div className="cards">{services.map(([t,I,img,d],i)=><article key={t}><div className="cardImg"><img src={`${A}${img}`}/><span>0{i+1}</span></div><div className="cardBody"><I/><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
<section className="feature wrap"><div><div className="eyebrow">FROM FOUNDATION TO FINISH</div><h2>Built with attention at every stage.</h2><p>Project requirements are translated into a clear work scope, coordinated execution and finishing activities, with progress and quality reviewed throughout the build.</p><a href="#process">See our execution approach <ArrowUpRight size={17}/></a></div><div className="featureImgs"><img src={`${A}05_Foundation_Rebar.jpg`}/><img src={`${A}06_Structure_Masonry_Construction.jpg`}/></div></section>
<section id="process" className="process"><div className="wrap processGrid"><div><div className="eyebrow gold">HOW WE WORK</div><h2>A clear path from idea to handover.</h2><p>Exact specifications, materials, quantities, timelines and commercial terms are finalized for each project through the applicable quotation, drawings and agreed documents.</p></div><div className="steps">{steps.map((s,i)=><div key={s}><b>{String(i+1).padStart(2,'0')}</b><span>{s}</span></div>)}</div></div></section>
<section className="quality wrap"><img src={`${A}07_Quality_Safety_Surveying.jpg`}/><div><div className="eyebrow">QUALITY & SAFETY</div><h2>Details matter on site.</h2><p>Our focus includes workmanship, material coordination, organized site execution, appropriate safety practices and timely maintenance support.</p><div className="qualityList"><div><b>Workmanship</b><span>Attention to dimensions, alignment, levels and finishes.</span></div><div><b>Site Coordination</b><span>Clear coordination among clients, supervisors, workers and vendors.</span></div><div><b>Maintenance</b><span>Periodic inspection and timely repair to protect long-term value.</span></div></div></div></section>
<section id="contact" className="contact"><div className="wrap contactGrid"><div><div className="eyebrow gold">LET'S BUILD TOGETHER</div><h2>Have a project in mind?</h2><p>Contact Babita Infra Projects for project discussions, quotations and construction requirements.</p><a className="primary" href="tel:7903528733">Call 7903528733 <Phone size={17}/></a></div><div className="contactCard"><a href="tel:7903528733"><Phone/><span><small>PHONE</small>7903528733</span></a><a href="mailto:babitainfraprojects@gmail.com"><Mail/><span><small>EMAIL</small>babitainfraprojects@gmail.com</span></a><div><MapPin/><span><small>ADDRESS</small>Lakhani Bigha, Dwarika Puri, Danapur Khagaul, Patna, Road Number 1E, 801105</span></div></div></div></section>
</main><footer><div className="wrap footer"><div><img src={`${A}logo.png`}/><span>Building Tomorrow Together</span></div><span>© 2026 Babita Infra Projects Pvt. Ltd.</span></div></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
